apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../../apps/test-dns-app

patches:
  - target: { kind: Service, name: test-dns-app }
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          external-dns.alpha.kubernetes.io/hostname: test.my-test.local
