apiVersion: v1
kind: Service
metadata:
  name: test-dns-app
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test.my-test.local
spec:
  selector:
    app: test-dns-app
  ports:
    - port: 80
      targetPort: 80
