apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- infrastructure/calico/kustomization.yaml
- infrastructure/kyverno/kustomization.yaml
- infrastructure/istio/kustomization.yaml
- apps/nginx