apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/kustomization.yaml
  - infrastructure/istio
  - infrastructure/calico
  - infrastructure/kyverno
  - apps/nginx
