apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/kustomization.yaml
  - infrastructure/istio/kustomization.yaml
  - infrastructure/calico/kustomization.yaml
  - infrastructure/kyverno/kustomization.yaml
  - infrastructure/nginx/kustomization.yaml
  - infrastructure/external-dns/kustomization.yaml
