apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../../apps/whoami-dns-app

patches:
  - target: { kind: Service, name: whoami-dns-app }
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          external-dns.alpha.kubernetes.io/hostname: whoami.my-test.local
