
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-dns-app
spec:
  replicas: 1
  selector:
    matchLabels: { app: whoami-dns-app }
  template:
    metadata:
      labels: { app: whoami-dns-app }
    spec:
      containers:
      - name: whoami
        image: jwilder/whoami
        ports: [{ containerPort: 80 }]
