apiVersion: v1
kind: Service
metadata:
  name: whoami-dns-app
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: whoami.my-test.local
spec:
  selector:
    app: whoami-dns-app
  ports:
    - port: 80
      targetPort: 80
